# see https://github.com/symplify/coding-standard for details
imports:
    # A. monorepo
    - { resource: '../../../coding-standard/config/symplify.yaml', ignore_errors: not_found }
    # B. installed as dependency or in PHAR
    - { resource: '../../vendor/symplify/coding-standard/config/symplify.yaml', ignore_errors: not_found }
