imports:
    - { resource: 'services/*' }

services:
    _defaults:
        autowire: true
        public: true

    Symplify\EasyCodingStandard\:
        resource: '../src'
        exclude:
            - '../src/Contract/*'
            - '../src/DependencyInjection/*'
            - '../src/HttpKernel/*'
            - '../src/Exception/*'
            - '../src/ValueObject/*'
            - '../src/Yaml/*'

    # Console
    Symfony\Component\Console\Terminal: null

    Symplify\PackageBuilder\Parameter\ParameterProvider: null
    Symplify\PackageBuilder\Php\TypeAnalyzer: null
    Symplify\SmartFileSystem\FileSystemGuard: null
    Symplify\SmartFileSystem\Finder\FinderSanitizer: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    PhpCsFixer\Tokenizer\Analyzer\NamespaceUsesAnalyzer: null
    PhpCsFixer\Tokenizer\Analyzer\NamespacesAnalyzer: null
    PhpCsFixer\Tokenizer\Analyzer\ArgumentsAnalyzer: null

    Symfony\Component\EventDispatcher\EventDispatcher: null
    Symplify\PackageBuilder\EventSubscriber\ParameterTypoProofreaderEventSubscriber: null

    # parameter corrections
    Symplify\PackageBuilder\Parameter\ParameterTypoProofreader:
        $correctToTypos:
            # param => [typos]
            skip:
                - '#skip.{1}#'
                - 'exclude'
                - 'ignore'
                - 'exclude_checkers'
                - 'exclude_checker'
                - 'excluded_checker'
                - 'excluded_checkers'
                - 'skip_checker'
                - 'skip_checkers'
            line_length:
                - 'line_lenght'
                - 'lineLength'
                - 'lineLenght'
                - 'line_size'
                - 'lineSize'
            exclude_files:
                - 'exclude_file'
                - 'excluded_file'
                - 'exclude_dir'
                - 'excluded_dir'
                - 'excluded_dirs'
                - 'exclude_path'
                - 'exclude_paths'
                - 'excluded_path'
                - 'excluded_paths'
                - 'skip_dirs'
                - 'skip_files'
